#!/bin/bash
g++ Guarana.cpp Turtle.cpp Antelope.cpp Fox.cpp main.cpp World.cpp Organism.cpp Wolf.cpp Human.cpp Animal.cpp Plant.cpp Grass.cpp Sheep.cpp Dandelion.cpp Hogweed.cpp Nightshade.cpp -lncurses -o main
./main